### ISSUE TITLE
Why not make it compatible with Arduino?

### ISSUE THREAD

**Issue by EUA** [kind3r/esp32-ble-gateway#8]
I am using Linux. I have arduino. I don't know why it requires VisualStudio etc.
Arduino could also program SPIFF partition. I wish someone could convert it to arduino and we could use this...

**Comment by Fusseldieb** [comment]
Traditional Arduinos are simply too slow to handle this. They are mostly based on 8-Bit processors.
Unless you mean those newer fancier boards, but it probably needs a major rewrite of this repo due to incompatible libraries.
The bluetooth calls, for instance, on the Arduino platform may be different on the esp one or vice-versa.

First things would probably abstract all the calls first to make it compabible "universally", but even this would require a rewrite of a lot of stuff.

I don't think it's feasible _for now_.
